<?php session_start(); 
$url_base = "http://localhost/apresenta-bikes";
?>

<body>
    
    <?php include "../header.php"; ?>
    
    <div class="container d-flex flex-column" style="margin-top: 25px">
        <div class="flex-fill text-justify">
            <h1 class="text-center">O QUE É MTB</h1>
            <p>Na maioria dos países de língua latina, para além de ciclismo de montanha, este esporte é também chamado de bicicleta todo o terreno, em sigla BTT, sendo esta a designação utilizada em Portugal e restantes países lusófonos, à exceção do Brasil, onde é conhecido popularmente pelos termos ingleses mountain bike ou mountain biking, comumente abreviado como MTB. No entanto, surgem por vezes as designações de ciclismo de montanha, e esporadicamente BTT, à semelhança da restante lusofonia.</p>
            <p>Curiosidade histórica foi a tentativa de introduzir em Portugal a designação VTT (do francês, Velo Tout Terrain), porque as primeiras bicicletas deste modelo tinham sido importadas deste país. A opção BTT resultou de polémica jornalística entre Alves Barbosa, ligado à FPC - Federação Portuguesa de Ciclismo, adepto da designação francesa, e Marcos Serra, co-fundador da FPCUB - Federação Portuguesa de Cicloturismo e Utilizadores de Bicicleta,que fez prevalecer a sigla BTT.</p>
            <p>O mountain bike é praticado em estradas de terra, trilhas de fazendas, trilhas em montanhas e dentro de parques e até na cidade. Esporte que envolve resistência, destreza, concentração e autossuficiência. Como é comum a prática do esporte em locais isolados, o aspecto de autossuficiência é importante para que o ciclista consiga realizar pequenos reparos em sua bicicleta, e concentração por ser um esporte que exige muito do psicológico para enfrentar os diversos obstáculos.</p>
        </div>
        <div class="flex-fill text-justify" style="margin-top: 15px">
            <h2 class="text-center">MODALIDADES</h2>
            <p>Há várias modalidades esportivas que podem ser incluídas na categoria Mountain Bike. O equipamento mínimo em todas elas, além de uma bicicleta adequada, é composto de capacete, luvas, uma câmara-de-ar reserva, bomba-de-ar, água (mochila com depósito ou cantil encaixado na bicicleta, com água ou mistura isotónica) e alimentos (geralmente barras de cereal, frutas ou algo igualmente rico em carboidratos e fácil de carregar). E o mais importante: por ser um esporte, de maneira geral, individual, é de extrema importância que o ciclista possua conhecimentos básicos de manutenção e reparo de bicicletas.</p>
            <p><h4><strong>Cross-country ou XCO:</strong></h4> É a prova disputada em estradas de terra,que possuem um alto nível de decidas e subidas técnicas com pedras e raízes,geralmente as provas de xco não são muito longas iguais as de maratonas,apresentam em torno de 30 a 40 km mas em percursos técnicos e pesados.Uma das provas mais importantes de xco é a copa do mundo,que tem melhorado a cada ano.</p>
            <p><h4><strong>Trip Trail, Maratona ou XCM:</strong></h4> É o tipo de prova em que o percurso é longo e leva de um ponto a outro, que pode ser ou não o mesmo do início da prova. Sendo no mesmo ponto, você só dá uma volta. Tem o nome Trip Trail porque é praticamente uma viagem por trilhas e estradas de terra. Quando o percurso é bem longo, pode ser chamado também de Maratona e chega a levar dois ou até três dias. Exemplos nacionais de provas dessa modalidade são o Big Biker e o MTB Trip Trail Ecomotion. Esse tipo de prova pode compor uma das modalidades de um rali, sendo as outras com veículos automotores - como é o caso do Cerapió(ou Piocerá). Outras vezes, uma prova de Trip Trail compõe um dos trechos de uma Corrida de Aventura, como por exemplo o Ecomotion Pro. As trilhas feitas por lazer pelos entusiastas do Mountain Bike costumam ter a característica de um trip trail.</p>
            <p><h4><strong>Singletrack:</strong></h4> uma modalidade de Mountain Bike praticada em terrenos de terra, acidentados com montanhas e trilhas, muitas vezes dentro de matas fechadas. É uma versão ciclística do double track ou fire road que é praticado com veículos que possuem quatro rodas, ou os off-roads. Singletrack é a interação de Mountain Biking com a Natureza, desfrutar do esporte com um ambiente as vezes inóspito.</p>
            <p><h4><strong>XCE:</strong></h4> é uma modalidade disputada geralmente em um circuito menor que o XCO, mais rápido, e com mais obstáculos onde o atleta é obrigado a fazer muita força para conseguir o melhor tempo. Cada atleta tem direito a uma volta rápida para marcar seu tempo oficial, depois, são efetuadas baterias classificatórias com quatro atletas, classificando os dois atletas mais rápidos, até que se dispute a final com quatro atletas.[2][3]</p>
            <p><h4><strong>Downhill ou DH:</strong></h4> No downhill, o ciclista passa por um percurso em descida, com no máximo algumas poucas retas, precisando passar por terreno bastante irregular, natural ou artificial, com jumps (pontos de salto), gaps (vãos a serem transpostos com ou sem ajuda de rampa) e drops (grandes degraus onde o ciclista se deixa "cair" para transpor), enfrentando situações de bastante risco. Nesse tipo de prova costuma-se usar um capacete full-face (capacete fechado que protege o queixo, parecido com o de motociclismo), joelheira com caneleira e muitas vezes colete e cotoveleira. Os ciclistas descem um a um, com tomada de tempo individual. Um exemplo é o Campeonato Brasileiro de Downhill, organizado pela Confederação Brasileira de Mountain Bike (CBMTB.COM).</p>
            <p><h4><strong>Freeride:</strong></h4> Uma variação do Downhill, o Freeride é utilizado como forma de lazer, tendo como principal diferença a utilização de terrenos variados, em vez de apenas descidas, além dos passeios chamados north shores - que consistem em andar por cima de árvores caídas ou por trajetos no alto de madeiras, criados dentro de florestas. Como consequência, a bicicleta de Freeride apresenta algumas variações em relação ao Downhill, como por exemplo o uso de mais de uma coroa (na relação de marchas dianteira). Os passeios de Freeride dentro das cidades são chamados comummente de Urban Assault e usam obstáculos urbanos, frequentemente escadarias, além de obstáculos construídos de forma fixa ou obstáculos removíveis que são montados na hora e levados embora depois. Downhill, Freeride e 4X são considerados por seus praticantes como "o lado extremo do ciclismo".</p>
            <p><h4><strong>4X:</strong></h4> O 4X (lê-se four cross)é uma modalidade que possui obstáculos derivados do BMX em um terreno inclinado, tendo largada com gate no estilo BMX, onde quatro competidores descem simultaneamente. Deriva do BMX e do Dual Slalom - uma modalidade em que desciam dois competidores por vez e que era mais parecida com o Downhill. O Dual Slalom caiu em desuso com a introdução do 4X. Os pilotos de 4X costumam vir tanto do BMX como do Downhill. É uma modalidade de ciclismo que tem caído nas graças da TV aberta, tendo eventuais transmissões pela Rede Globo.</p>
            <p><h4><strong>Trial:</strong></h4> Nessa modalidade, o percurso consiste de obstáculos diversos para serem transpostos pelos competidores, que podem ser compostos de cavaletes, troncos, pedras, latões, muros e até carros. As bicicletas costumam ter quadros pequenos, reforçados, freios hidráulicos, protetor debaixo da coroa e pneus mais vazios, principalmente o traseiro, que além de mais vazio não tem câmara, é mais largo e composto de uma borracha bem mole, para aumentar o grip. Os competidores começam com determinada pontuação e perdem pontos a cada vez que tocam o chão com algum dos pés.</p>
            <p><h4><strong>BMX:</strong></h4> O nome deriva de Bicycle Motocross, pois as primeiras bicicletas imitavam essas motos. As provas são disputadas em circuito com várias voltas e obstáculos como jumps e curvas de parede, geralmente por competidores muito jovens, com bicicletas menores, de aro 20". Há outras modalidades relacionadas ao BMX, como por exemplo Vertical e Freestyle.</p>
            <p><h4><strong>Enduro de Regularidade:</strong></h4> É a prova disputada com uma planilha, que contém as referências a serem seguidas e a média horária estipulada pela organização. O objetivo desse tipo de competição não é ser o primeiro a chegar, mas sim ser o mais regular. Chegar no horário exato concede ao competidor ZERO pontos. Para cada segundo de atraso ele será penalizado com UM ponto e para cada segundo adiantado, TRÊS pontos. O vencedor será aquele que obtiver o menor número de pontos. Normalmente é disputado em duplas. A prova é disputada em estradas abertas e trilhas fechadas.</p>
            <p><h4><strong>Enduro Mountain Bike:</strong></h4> Enduro é uma modalidade do MTB onde há predominância de descidas nos percursos em relação as subidas. O objetivo da modalidade 'testar a técnica de pilotagem em conjunto com a resistência do piloto.</p>
        </div>
    </div>
    <?php include "../footer.php"; ?>

</body>